services:

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: watchtower-frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - watchtower-net

  # Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: watchtower-backend
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL:      jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - watchtower-net


  #  Database 
  db:
    image: postgres:16-alpine
    container_name: watchtower-db
    environment:
      POSTGRES_DB:       ${POSTGRES_DB}
      POSTGRES_USER:     ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"              # remove in prod later (don't want my db to be exposed)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - watchtower-net
 
volumes:
  postgres_data:
 
networks:
  watchtower-net:
    driver: bridge