management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, env, beans, mappings, loggers
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  info:
    git:
      mode: full